<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.kato.pro</groupId>
        <artifactId>kato-pivot</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>kato-risk</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>kato-risk-client</module>
        <module>kato-risk-server</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <groovy.version>3.0.9</groovy.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Groovy 脚本引擎 -->
            <dependency>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-all</artifactId>
                <version>${groovy.version}</version>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
