// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

/**
 * Protobuf type {@code com.kato.pro.risk.GrpcGroovyTestResult}
 */
public final class GrpcGroovyTestResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.kato.pro.risk.GrpcGroovyTestResult)
    GrpcGroovyTestResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcGroovyTestResult.newBuilder() to construct.
  private GrpcGroovyTestResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcGroovyTestResult() {
    testCaseName_ = "";
    output_ = "";
    errorMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcGroovyTestResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcGroovyTestResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            testCaseName_ = s;
            break;
          }
          case 16: {

            passed_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            output_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          case 40: {

            executionTimeMs_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kato.pro.risk.grpc.GrpcGroovyTestResult.class, com.kato.pro.risk.grpc.GrpcGroovyTestResult.Builder.class);
  }

  public static final int TEST_CASE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object testCaseName_;
  /**
   * <code>string test_case_name = 1;</code>
   * @return The testCaseName.
   */
  @java.lang.Override
  public java.lang.String getTestCaseName() {
    java.lang.Object ref = testCaseName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testCaseName_ = s;
      return s;
    }
  }
  /**
   * <code>string test_case_name = 1;</code>
   * @return The bytes for testCaseName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestCaseNameBytes() {
    java.lang.Object ref = testCaseName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testCaseName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSED_FIELD_NUMBER = 2;
  private boolean passed_;
  /**
   * <code>bool passed = 2;</code>
   * @return The passed.
   */
  @java.lang.Override
  public boolean getPassed() {
    return passed_;
  }

  public static final int OUTPUT_FIELD_NUMBER = 3;
  private volatile java.lang.Object output_;
  /**
   * <code>string output = 3;</code>
   * @return The output.
   */
  @java.lang.Override
  public java.lang.String getOutput() {
    java.lang.Object ref = output_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      output_ = s;
      return s;
    }
  }
  /**
   * <code>string output = 3;</code>
   * @return The bytes for output.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputBytes() {
    java.lang.Object ref = output_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      output_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object errorMessage_;
  /**
   * <code>string error_message = 4;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 4;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTION_TIME_MS_FIELD_NUMBER = 5;
  private long executionTimeMs_;
  /**
   * <code>int64 execution_time_ms = 5;</code>
   * @return The executionTimeMs.
   */
  @java.lang.Override
  public long getExecutionTimeMs() {
    return executionTimeMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testCaseName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testCaseName_);
    }
    if (passed_ != false) {
      output.writeBool(2, passed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(output_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, output_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorMessage_);
    }
    if (executionTimeMs_ != 0L) {
      output.writeInt64(5, executionTimeMs_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testCaseName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, testCaseName_);
    }
    if (passed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, passed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(output_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, output_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorMessage_);
    }
    if (executionTimeMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, executionTimeMs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kato.pro.risk.grpc.GrpcGroovyTestResult)) {
      return super.equals(obj);
    }
    com.kato.pro.risk.grpc.GrpcGroovyTestResult other = (com.kato.pro.risk.grpc.GrpcGroovyTestResult) obj;

    if (!getTestCaseName()
        .equals(other.getTestCaseName())) return false;
    if (getPassed()
        != other.getPassed()) return false;
    if (!getOutput()
        .equals(other.getOutput())) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (getExecutionTimeMs()
        != other.getExecutionTimeMs()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEST_CASE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTestCaseName().hashCode();
    hash = (37 * hash) + PASSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPassed());
    hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
    hash = (53 * hash) + getOutput().hashCode();
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + EXECUTION_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionTimeMs());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kato.pro.risk.grpc.GrpcGroovyTestResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.kato.pro.risk.GrpcGroovyTestResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.kato.pro.risk.GrpcGroovyTestResult)
      com.kato.pro.risk.grpc.GrpcGroovyTestResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kato.pro.risk.grpc.GrpcGroovyTestResult.class, com.kato.pro.risk.grpc.GrpcGroovyTestResult.Builder.class);
    }

    // Construct using com.kato.pro.risk.grpc.GrpcGroovyTestResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      testCaseName_ = "";

      passed_ = false;

      output_ = "";

      errorMessage_ = "";

      executionTimeMs_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestResult_descriptor;
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcGroovyTestResult getDefaultInstanceForType() {
      return com.kato.pro.risk.grpc.GrpcGroovyTestResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcGroovyTestResult build() {
      com.kato.pro.risk.grpc.GrpcGroovyTestResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcGroovyTestResult buildPartial() {
      com.kato.pro.risk.grpc.GrpcGroovyTestResult result = new com.kato.pro.risk.grpc.GrpcGroovyTestResult(this);
      result.testCaseName_ = testCaseName_;
      result.passed_ = passed_;
      result.output_ = output_;
      result.errorMessage_ = errorMessage_;
      result.executionTimeMs_ = executionTimeMs_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kato.pro.risk.grpc.GrpcGroovyTestResult) {
        return mergeFrom((com.kato.pro.risk.grpc.GrpcGroovyTestResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kato.pro.risk.grpc.GrpcGroovyTestResult other) {
      if (other == com.kato.pro.risk.grpc.GrpcGroovyTestResult.getDefaultInstance()) return this;
      if (!other.getTestCaseName().isEmpty()) {
        testCaseName_ = other.testCaseName_;
        onChanged();
      }
      if (other.getPassed() != false) {
        setPassed(other.getPassed());
      }
      if (!other.getOutput().isEmpty()) {
        output_ = other.output_;
        onChanged();
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.getExecutionTimeMs() != 0L) {
        setExecutionTimeMs(other.getExecutionTimeMs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kato.pro.risk.grpc.GrpcGroovyTestResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kato.pro.risk.grpc.GrpcGroovyTestResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object testCaseName_ = "";
    /**
     * <code>string test_case_name = 1;</code>
     * @return The testCaseName.
     */
    public java.lang.String getTestCaseName() {
      java.lang.Object ref = testCaseName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testCaseName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_case_name = 1;</code>
     * @return The bytes for testCaseName.
     */
    public com.google.protobuf.ByteString
        getTestCaseNameBytes() {
      java.lang.Object ref = testCaseName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testCaseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_case_name = 1;</code>
     * @param value The testCaseName to set.
     * @return This builder for chaining.
     */
    public Builder setTestCaseName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testCaseName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_case_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestCaseName() {
      
      testCaseName_ = getDefaultInstance().getTestCaseName();
      onChanged();
      return this;
    }
    /**
     * <code>string test_case_name = 1;</code>
     * @param value The bytes for testCaseName to set.
     * @return This builder for chaining.
     */
    public Builder setTestCaseNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testCaseName_ = value;
      onChanged();
      return this;
    }

    private boolean passed_ ;
    /**
     * <code>bool passed = 2;</code>
     * @return The passed.
     */
    @java.lang.Override
    public boolean getPassed() {
      return passed_;
    }
    /**
     * <code>bool passed = 2;</code>
     * @param value The passed to set.
     * @return This builder for chaining.
     */
    public Builder setPassed(boolean value) {
      
      passed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool passed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassed() {
      
      passed_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object output_ = "";
    /**
     * <code>string output = 3;</code>
     * @return The output.
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string output = 3;</code>
     * @return The bytes for output.
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string output = 3;</code>
     * @param value The output to set.
     * @return This builder for chaining.
     */
    public Builder setOutput(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      output_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string output = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutput() {
      
      output_ = getDefaultInstance().getOutput();
      onChanged();
      return this;
    }
    /**
     * <code>string output = 3;</code>
     * @param value The bytes for output to set.
     * @return This builder for chaining.
     */
    public Builder setOutputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      output_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }

    private long executionTimeMs_ ;
    /**
     * <code>int64 execution_time_ms = 5;</code>
     * @return The executionTimeMs.
     */
    @java.lang.Override
    public long getExecutionTimeMs() {
      return executionTimeMs_;
    }
    /**
     * <code>int64 execution_time_ms = 5;</code>
     * @param value The executionTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionTimeMs(long value) {
      
      executionTimeMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 execution_time_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionTimeMs() {
      
      executionTimeMs_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.kato.pro.risk.GrpcGroovyTestResult)
  }

  // @@protoc_insertion_point(class_scope:com.kato.pro.risk.GrpcGroovyTestResult)
  private static final com.kato.pro.risk.grpc.GrpcGroovyTestResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kato.pro.risk.grpc.GrpcGroovyTestResult();
  }

  public static com.kato.pro.risk.grpc.GrpcGroovyTestResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcGroovyTestResult>
      PARSER = new com.google.protobuf.AbstractParser<GrpcGroovyTestResult>() {
    @java.lang.Override
    public GrpcGroovyTestResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcGroovyTestResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcGroovyTestResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcGroovyTestResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kato.pro.risk.grpc.GrpcGroovyTestResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

