// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

/**
 * Protobuf type {@code com.kato.pro.risk.GrpcRiskResponse}
 */
public final class GrpcRiskResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.kato.pro.risk.GrpcRiskResponse)
    GrpcRiskResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcRiskResponse.newBuilder() to construct.
  private GrpcRiskResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcRiskResponse() {
    requestId_ = "";
    action_ = "";
    reasonCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcRiskResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcRiskResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 24: {

            score_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reasonCodes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            reasonCodes_.add(s);
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              extData_ = com.google.protobuf.MapField.newMapField(
                  ExtDataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            extData__ = input.readMessage(
                ExtDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            extData_.getMutableMap().put(
                extData__.getKey(), extData__.getValue());
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reasonCodes_ = reasonCodes_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetExtData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcRiskResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kato.pro.risk.grpc.GrpcRiskResponse.class, com.kato.pro.risk.grpc.GrpcRiskResponse.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object action_;
  /**
   * <pre>
   * PASS/BLOCK/REVIEW
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PASS/BLOCK/REVIEW
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORE_FIELD_NUMBER = 3;
  private int score_;
  /**
   * <pre>
   * 0-100
   * </pre>
   *
   * <code>int32 score = 3;</code>
   * @return The score.
   */
  @java.lang.Override
  public int getScore() {
    return score_;
  }

  public static final int REASON_CODES_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList reasonCodes_;
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @return A list containing the reasonCodes.
   */
  public com.google.protobuf.ProtocolStringList
      getReasonCodesList() {
    return reasonCodes_;
  }
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @return The count of reasonCodes.
   */
  public int getReasonCodesCount() {
    return reasonCodes_.size();
  }
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @param index The index of the element to return.
   * @return The reasonCodes at the given index.
   */
  public java.lang.String getReasonCodes(int index) {
    return reasonCodes_.get(index);
  }
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reasonCodes at the given index.
   */
  public com.google.protobuf.ByteString
      getReasonCodesBytes(int index) {
    return reasonCodes_.getByteString(index);
  }

  public static final int EXT_DATA_FIELD_NUMBER = 5;
  private static final class ExtDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcRiskResponse_ExtDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> extData_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExtData() {
    if (extData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtDataDefaultEntryHolder.defaultEntry);
    }
    return extData_;
  }

  public int getExtDataCount() {
    return internalGetExtData().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */

  @java.lang.Override
  public boolean containsExtData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetExtData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExtData() {
    return getExtDataMap();
  }
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getExtDataMap() {
    return internalGetExtData().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */
  @java.lang.Override

  public java.lang.String getExtDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */
  @java.lang.Override

  public java.lang.String getExtDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 6;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 6;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, action_);
    }
    if (score_ != 0) {
      output.writeInt32(3, score_);
    }
    for (int i = 0; i < reasonCodes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, reasonCodes_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetExtData(),
        ExtDataDefaultEntryHolder.defaultEntry,
        5);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, message_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, action_);
    }
    if (score_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, score_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < reasonCodes_.size(); i++) {
        dataSize += computeStringSizeNoTag(reasonCodes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReasonCodesList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExtData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      extData__ = ExtDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, extData__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, message_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kato.pro.risk.grpc.GrpcRiskResponse)) {
      return super.equals(obj);
    }
    com.kato.pro.risk.grpc.GrpcRiskResponse other = (com.kato.pro.risk.grpc.GrpcRiskResponse) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (getScore()
        != other.getScore()) return false;
    if (!getReasonCodesList()
        .equals(other.getReasonCodesList())) return false;
    if (!internalGetExtData().equals(
        other.internalGetExtData())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getScore();
    if (getReasonCodesCount() > 0) {
      hash = (37 * hash) + REASON_CODES_FIELD_NUMBER;
      hash = (53 * hash) + getReasonCodesList().hashCode();
    }
    if (!internalGetExtData().getMap().isEmpty()) {
      hash = (37 * hash) + EXT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtData().hashCode();
    }
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcRiskResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kato.pro.risk.grpc.GrpcRiskResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.kato.pro.risk.GrpcRiskResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.kato.pro.risk.GrpcRiskResponse)
      com.kato.pro.risk.grpc.GrpcRiskResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetExtData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableExtData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcRiskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kato.pro.risk.grpc.GrpcRiskResponse.class, com.kato.pro.risk.grpc.GrpcRiskResponse.Builder.class);
    }

    // Construct using com.kato.pro.risk.grpc.GrpcRiskResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      action_ = "";

      score_ = 0;

      reasonCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableExtData().clear();
      message_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor;
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcRiskResponse getDefaultInstanceForType() {
      return com.kato.pro.risk.grpc.GrpcRiskResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcRiskResponse build() {
      com.kato.pro.risk.grpc.GrpcRiskResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcRiskResponse buildPartial() {
      com.kato.pro.risk.grpc.GrpcRiskResponse result = new com.kato.pro.risk.grpc.GrpcRiskResponse(this);
      int from_bitField0_ = bitField0_;
      result.requestId_ = requestId_;
      result.action_ = action_;
      result.score_ = score_;
      if (((bitField0_ & 0x00000001) != 0)) {
        reasonCodes_ = reasonCodes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.reasonCodes_ = reasonCodes_;
      result.extData_ = internalGetExtData();
      result.extData_.makeImmutable();
      result.message_ = message_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kato.pro.risk.grpc.GrpcRiskResponse) {
        return mergeFrom((com.kato.pro.risk.grpc.GrpcRiskResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kato.pro.risk.grpc.GrpcRiskResponse other) {
      if (other == com.kato.pro.risk.grpc.GrpcRiskResponse.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (other.getScore() != 0) {
        setScore(other.getScore());
      }
      if (!other.reasonCodes_.isEmpty()) {
        if (reasonCodes_.isEmpty()) {
          reasonCodes_ = other.reasonCodes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureReasonCodesIsMutable();
          reasonCodes_.addAll(other.reasonCodes_);
        }
        onChanged();
      }
      internalGetMutableExtData().mergeFrom(
          other.internalGetExtData());
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kato.pro.risk.grpc.GrpcRiskResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kato.pro.risk.grpc.GrpcRiskResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestId_ = "";
    /**
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <pre>
     * PASS/BLOCK/REVIEW
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * PASS/BLOCK/REVIEW
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PASS/BLOCK/REVIEW
     * </pre>
     *
     * <code>string action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PASS/BLOCK/REVIEW
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PASS/BLOCK/REVIEW
     * </pre>
     *
     * <code>string action = 2;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private int score_ ;
    /**
     * <pre>
     * 0-100
     * </pre>
     *
     * <code>int32 score = 3;</code>
     * @return The score.
     */
    @java.lang.Override
    public int getScore() {
      return score_;
    }
    /**
     * <pre>
     * 0-100
     * </pre>
     *
     * <code>int32 score = 3;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(int value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-100
     * </pre>
     *
     * <code>int32 score = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      
      score_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList reasonCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReasonCodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reasonCodes_ = new com.google.protobuf.LazyStringArrayList(reasonCodes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @return A list containing the reasonCodes.
     */
    public com.google.protobuf.ProtocolStringList
        getReasonCodesList() {
      return reasonCodes_.getUnmodifiableView();
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @return The count of reasonCodes.
     */
    public int getReasonCodesCount() {
      return reasonCodes_.size();
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @param index The index of the element to return.
     * @return The reasonCodes at the given index.
     */
    public java.lang.String getReasonCodes(int index) {
      return reasonCodes_.get(index);
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the reasonCodes at the given index.
     */
    public com.google.protobuf.ByteString
        getReasonCodesBytes(int index) {
      return reasonCodes_.getByteString(index);
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @param index The index to set the value at.
     * @param value The reasonCodes to set.
     * @return This builder for chaining.
     */
    public Builder setReasonCodes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReasonCodesIsMutable();
      reasonCodes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @param value The reasonCodes to add.
     * @return This builder for chaining.
     */
    public Builder addReasonCodes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReasonCodesIsMutable();
      reasonCodes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @param values The reasonCodes to add.
     * @return This builder for chaining.
     */
    public Builder addAllReasonCodes(
        java.lang.Iterable<java.lang.String> values) {
      ensureReasonCodesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, reasonCodes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasonCodes() {
      reasonCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason_codes = 4;</code>
     * @param value The bytes of the reasonCodes to add.
     * @return This builder for chaining.
     */
    public Builder addReasonCodesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReasonCodesIsMutable();
      reasonCodes_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extData_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExtData() {
      if (extData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtDataDefaultEntryHolder.defaultEntry);
      }
      return extData_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableExtData() {
      onChanged();;
      if (extData_ == null) {
        extData_ = com.google.protobuf.MapField.newMapField(
            ExtDataDefaultEntryHolder.defaultEntry);
      }
      if (!extData_.isMutable()) {
        extData_ = extData_.copy();
      }
      return extData_;
    }

    public int getExtDataCount() {
      return internalGetExtData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */

    @java.lang.Override
    public boolean containsExtData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExtData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtData() {
      return getExtDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getExtDataMap() {
      return internalGetExtData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getExtDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getExtDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearExtData() {
      internalGetMutableExtData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */

    public Builder removeExtData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableExtData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableExtData() {
      return internalGetMutableExtData().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */
    public Builder putExtData(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableExtData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; ext_data = 5;</code>
     */

    public Builder putAllExtData(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExtData().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 6;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 6;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 6;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 6;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.kato.pro.risk.GrpcRiskResponse)
  }

  // @@protoc_insertion_point(class_scope:com.kato.pro.risk.GrpcRiskResponse)
  private static final com.kato.pro.risk.grpc.GrpcRiskResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kato.pro.risk.grpc.GrpcRiskResponse();
  }

  public static com.kato.pro.risk.grpc.GrpcRiskResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcRiskResponse>
      PARSER = new com.google.protobuf.AbstractParser<GrpcRiskResponse>() {
    @java.lang.Override
    public GrpcRiskResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcRiskResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcRiskResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcRiskResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kato.pro.risk.grpc.GrpcRiskResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

