// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

public interface GrpcGroovyTestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kato.pro.risk.GrpcGroovyTestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string script_content = 1;</code>
   * @return The scriptContent.
   */
  java.lang.String getScriptContent();
  /**
   * <code>string script_content = 1;</code>
   * @return The bytes for scriptContent.
   */
  com.google.protobuf.ByteString
      getScriptContentBytes();

  /**
   * <code>string test_case_name = 2;</code>
   * @return The testCaseName.
   */
  java.lang.String getTestCaseName();
  /**
   * <code>string test_case_name = 2;</code>
   * @return The bytes for testCaseName.
   */
  com.google.protobuf.ByteString
      getTestCaseNameBytes();

  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */
  int getInputContextCount();
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */
  boolean containsInputContext(
      java.lang.String key);
  /**
   * Use {@link #getInputContextMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getInputContext();
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getInputContextMap();
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */

  java.lang.String getInputContextOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */

  java.lang.String getInputContextOrThrow(
      java.lang.String key);
}
