// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

public final class Risk {
  private Risk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcRiskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcRiskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcRiskRequest_ExtDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcRiskRequest_ExtDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcRiskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcRiskResponse_ExtDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcRiskResponse_ExtDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_InputContextEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_InputContextEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kato_pro_risk_GrpcGroovyTestResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kato_pro_risk_GrpcGroovyTestResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrisk.proto\022\021com.kato.pro.risk\"\327\001\n\017Grpc" +
      "RiskRequest\022\022\n\nrequest_id\030\001 \001(\t\022\r\n\005scene" +
      "\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\t\022\021\n\tdevice_id\030\004 \001" +
      "(\t\022\n\n\002ip\030\005 \001(\t\022A\n\010ext_data\030\006 \003(\0132/.com.k" +
      "ato.pro.risk.GrpcRiskRequest.ExtDataEntr" +
      "y\032.\n\014ExtDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"\340\001\n\020GrpcRiskResponse\022\022\n\nreques" +
      "t_id\030\001 \001(\t\022\016\n\006action\030\002 \001(\t\022\r\n\005score\030\003 \001(" +
      "\005\022\024\n\014reason_codes\030\004 \003(\t\022B\n\010ext_data\030\005 \003(" +
      "\01320.com.kato.pro.risk.GrpcRiskResponse.E" +
      "xtDataEntry\022\017\n\007message\030\006 \001(\t\032.\n\014ExtDataE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\317\001\n" +
      "\025GrpcGroovyTestRequest\022\026\n\016script_content" +
      "\030\001 \001(\t\022\026\n\016test_case_name\030\002 \001(\t\022Q\n\rinput_" +
      "context\030\003 \003(\0132:.com.kato.pro.risk.GrpcGr" +
      "oovyTestRequest.InputContextEntry\0323\n\021Inp" +
      "utContextEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\"\200\001\n\024GrpcGroovyTestResult\022\026\n\016test_" +
      "case_name\030\001 \001(\t\022\016\n\006passed\030\002 \001(\010\022\016\n\006outpu" +
      "t\030\003 \001(\t\022\025\n\rerror_message\030\004 \001(\t\022\031\n\021execut" +
      "ion_time_ms\030\005 \001(\0032\313\001\n\020RiskCheckService\022P" +
      "\n\005check\022\".com.kato.pro.risk.GrpcRiskRequ" +
      "est\032#.com.kato.pro.risk.GrpcRiskResponse" +
      "\022e\n\020testGroovyScript\022(.com.kato.pro.risk" +
      ".GrpcGroovyTestRequest\032\'.com.kato.pro.ri" +
      "sk.GrpcGroovyTestResultB\032\n\026com.kato.pro." +
      "risk.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kato_pro_risk_GrpcRiskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kato_pro_risk_GrpcRiskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcRiskRequest_descriptor,
        new java.lang.String[] { "RequestId", "Scene", "UserId", "DeviceId", "Ip", "ExtData", });
    internal_static_com_kato_pro_risk_GrpcRiskRequest_ExtDataEntry_descriptor =
      internal_static_com_kato_pro_risk_GrpcRiskRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_kato_pro_risk_GrpcRiskRequest_ExtDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcRiskRequest_ExtDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kato_pro_risk_GrpcRiskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor,
        new java.lang.String[] { "RequestId", "Action", "Score", "ReasonCodes", "ExtData", "Message", });
    internal_static_com_kato_pro_risk_GrpcRiskResponse_ExtDataEntry_descriptor =
      internal_static_com_kato_pro_risk_GrpcRiskResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_kato_pro_risk_GrpcRiskResponse_ExtDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcRiskResponse_ExtDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor,
        new java.lang.String[] { "ScriptContent", "TestCaseName", "InputContext", });
    internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_InputContextEntry_descriptor =
      internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_InputContextEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_InputContextEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_kato_pro_risk_GrpcGroovyTestResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_kato_pro_risk_GrpcGroovyTestResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kato_pro_risk_GrpcGroovyTestResult_descriptor,
        new java.lang.String[] { "TestCaseName", "Passed", "Output", "ErrorMessage", "ExecutionTimeMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
