spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kato_langchain?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:root}

logging:
  level:
    com.kato.pro.langchain: DEBUG
