// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

public interface GrpcRiskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kato.pro.risk.GrpcRiskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * REGISTER/LOGIN/MARKETING/ORDER/PAYMENT/REFUND
   * </pre>
   *
   * <code>string scene = 2;</code>
   * @return The scene.
   */
  java.lang.String getScene();
  /**
   * <pre>
   * REGISTER/LOGIN/MARKETING/ORDER/PAYMENT/REFUND
   * </pre>
   *
   * <code>string scene = 2;</code>
   * @return The bytes for scene.
   */
  com.google.protobuf.ByteString
      getSceneBytes();

  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string device_id = 4;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 4;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string ip = 5;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 5;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext_data = 6;</code>
   */
  int getExtDataCount();
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext_data = 6;</code>
   */
  boolean containsExtData(
      java.lang.String key);
  /**
   * Use {@link #getExtDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtData();
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext_data = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtDataMap();
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext_data = 6;</code>
   */

  java.lang.String getExtDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext_data = 6;</code>
   */

  java.lang.String getExtDataOrThrow(
      java.lang.String key);
}
