// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

public interface GrpcGroovyTestResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kato.pro.risk.GrpcGroovyTestResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test_case_name = 1;</code>
   * @return The testCaseName.
   */
  java.lang.String getTestCaseName();
  /**
   * <code>string test_case_name = 1;</code>
   * @return The bytes for testCaseName.
   */
  com.google.protobuf.ByteString
      getTestCaseNameBytes();

  /**
   * <code>bool passed = 2;</code>
   * @return The passed.
   */
  boolean getPassed();

  /**
   * <code>string output = 3;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 3;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();

  /**
   * <code>string error_message = 4;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 4;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>int64 execution_time_ms = 5;</code>
   * @return The executionTimeMs.
   */
  long getExecutionTimeMs();
}
