// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

/**
 * Protobuf type {@code com.kato.pro.risk.GrpcGroovyTestRequest}
 */
public final class GrpcGroovyTestRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.kato.pro.risk.GrpcGroovyTestRequest)
    GrpcGroovyTestRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcGroovyTestRequest.newBuilder() to construct.
  private GrpcGroovyTestRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcGroovyTestRequest() {
    scriptContent_ = "";
    testCaseName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcGroovyTestRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcGroovyTestRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            scriptContent_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            testCaseName_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              inputContext_ = com.google.protobuf.MapField.newMapField(
                  InputContextDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            inputContext__ = input.readMessage(
                InputContextDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            inputContext_.getMutableMap().put(
                inputContext__.getKey(), inputContext__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetInputContext();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kato.pro.risk.grpc.GrpcGroovyTestRequest.class, com.kato.pro.risk.grpc.GrpcGroovyTestRequest.Builder.class);
  }

  public static final int SCRIPT_CONTENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object scriptContent_;
  /**
   * <code>string script_content = 1;</code>
   * @return The scriptContent.
   */
  @java.lang.Override
  public java.lang.String getScriptContent() {
    java.lang.Object ref = scriptContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scriptContent_ = s;
      return s;
    }
  }
  /**
   * <code>string script_content = 1;</code>
   * @return The bytes for scriptContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScriptContentBytes() {
    java.lang.Object ref = scriptContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scriptContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_CASE_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object testCaseName_;
  /**
   * <code>string test_case_name = 2;</code>
   * @return The testCaseName.
   */
  @java.lang.Override
  public java.lang.String getTestCaseName() {
    java.lang.Object ref = testCaseName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testCaseName_ = s;
      return s;
    }
  }
  /**
   * <code>string test_case_name = 2;</code>
   * @return The bytes for testCaseName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestCaseNameBytes() {
    java.lang.Object ref = testCaseName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testCaseName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_CONTEXT_FIELD_NUMBER = 3;
  private static final class InputContextDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_InputContextEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> inputContext_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetInputContext() {
    if (inputContext_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InputContextDefaultEntryHolder.defaultEntry);
    }
    return inputContext_;
  }

  public int getInputContextCount() {
    return internalGetInputContext().getMap().size();
  }
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */

  @java.lang.Override
  public boolean containsInputContext(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetInputContext().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInputContextMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getInputContext() {
    return getInputContextMap();
  }
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getInputContextMap() {
    return internalGetInputContext().getMap();
  }
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getInputContextOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInputContext().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * ctx 中的变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; input_context = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getInputContextOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInputContext().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scriptContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, scriptContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testCaseName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, testCaseName_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetInputContext(),
        InputContextDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scriptContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, scriptContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testCaseName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, testCaseName_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetInputContext().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      inputContext__ = InputContextDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, inputContext__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kato.pro.risk.grpc.GrpcGroovyTestRequest)) {
      return super.equals(obj);
    }
    com.kato.pro.risk.grpc.GrpcGroovyTestRequest other = (com.kato.pro.risk.grpc.GrpcGroovyTestRequest) obj;

    if (!getScriptContent()
        .equals(other.getScriptContent())) return false;
    if (!getTestCaseName()
        .equals(other.getTestCaseName())) return false;
    if (!internalGetInputContext().equals(
        other.internalGetInputContext())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCRIPT_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getScriptContent().hashCode();
    hash = (37 * hash) + TEST_CASE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTestCaseName().hashCode();
    if (!internalGetInputContext().getMap().isEmpty()) {
      hash = (37 * hash) + INPUT_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInputContext().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kato.pro.risk.grpc.GrpcGroovyTestRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.kato.pro.risk.GrpcGroovyTestRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.kato.pro.risk.GrpcGroovyTestRequest)
      com.kato.pro.risk.grpc.GrpcGroovyTestRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetInputContext();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableInputContext();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kato.pro.risk.grpc.GrpcGroovyTestRequest.class, com.kato.pro.risk.grpc.GrpcGroovyTestRequest.Builder.class);
    }

    // Construct using com.kato.pro.risk.grpc.GrpcGroovyTestRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      scriptContent_ = "";

      testCaseName_ = "";

      internalGetMutableInputContext().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kato.pro.risk.grpc.Risk.internal_static_com_kato_pro_risk_GrpcGroovyTestRequest_descriptor;
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcGroovyTestRequest getDefaultInstanceForType() {
      return com.kato.pro.risk.grpc.GrpcGroovyTestRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcGroovyTestRequest build() {
      com.kato.pro.risk.grpc.GrpcGroovyTestRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kato.pro.risk.grpc.GrpcGroovyTestRequest buildPartial() {
      com.kato.pro.risk.grpc.GrpcGroovyTestRequest result = new com.kato.pro.risk.grpc.GrpcGroovyTestRequest(this);
      int from_bitField0_ = bitField0_;
      result.scriptContent_ = scriptContent_;
      result.testCaseName_ = testCaseName_;
      result.inputContext_ = internalGetInputContext();
      result.inputContext_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kato.pro.risk.grpc.GrpcGroovyTestRequest) {
        return mergeFrom((com.kato.pro.risk.grpc.GrpcGroovyTestRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kato.pro.risk.grpc.GrpcGroovyTestRequest other) {
      if (other == com.kato.pro.risk.grpc.GrpcGroovyTestRequest.getDefaultInstance()) return this;
      if (!other.getScriptContent().isEmpty()) {
        scriptContent_ = other.scriptContent_;
        onChanged();
      }
      if (!other.getTestCaseName().isEmpty()) {
        testCaseName_ = other.testCaseName_;
        onChanged();
      }
      internalGetMutableInputContext().mergeFrom(
          other.internalGetInputContext());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kato.pro.risk.grpc.GrpcGroovyTestRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kato.pro.risk.grpc.GrpcGroovyTestRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object scriptContent_ = "";
    /**
     * <code>string script_content = 1;</code>
     * @return The scriptContent.
     */
    public java.lang.String getScriptContent() {
      java.lang.Object ref = scriptContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scriptContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string script_content = 1;</code>
     * @return The bytes for scriptContent.
     */
    public com.google.protobuf.ByteString
        getScriptContentBytes() {
      java.lang.Object ref = scriptContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scriptContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string script_content = 1;</code>
     * @param value The scriptContent to set.
     * @return This builder for chaining.
     */
    public Builder setScriptContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scriptContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string script_content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScriptContent() {
      
      scriptContent_ = getDefaultInstance().getScriptContent();
      onChanged();
      return this;
    }
    /**
     * <code>string script_content = 1;</code>
     * @param value The bytes for scriptContent to set.
     * @return This builder for chaining.
     */
    public Builder setScriptContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scriptContent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testCaseName_ = "";
    /**
     * <code>string test_case_name = 2;</code>
     * @return The testCaseName.
     */
    public java.lang.String getTestCaseName() {
      java.lang.Object ref = testCaseName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testCaseName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_case_name = 2;</code>
     * @return The bytes for testCaseName.
     */
    public com.google.protobuf.ByteString
        getTestCaseNameBytes() {
      java.lang.Object ref = testCaseName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testCaseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_case_name = 2;</code>
     * @param value The testCaseName to set.
     * @return This builder for chaining.
     */
    public Builder setTestCaseName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testCaseName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_case_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestCaseName() {
      
      testCaseName_ = getDefaultInstance().getTestCaseName();
      onChanged();
      return this;
    }
    /**
     * <code>string test_case_name = 2;</code>
     * @param value The bytes for testCaseName to set.
     * @return This builder for chaining.
     */
    public Builder setTestCaseNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testCaseName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> inputContext_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetInputContext() {
      if (inputContext_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputContextDefaultEntryHolder.defaultEntry);
      }
      return inputContext_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableInputContext() {
      onChanged();;
      if (inputContext_ == null) {
        inputContext_ = com.google.protobuf.MapField.newMapField(
            InputContextDefaultEntryHolder.defaultEntry);
      }
      if (!inputContext_.isMutable()) {
        inputContext_ = inputContext_.copy();
      }
      return inputContext_;
    }

    public int getInputContextCount() {
      return internalGetInputContext().getMap().size();
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */

    @java.lang.Override
    public boolean containsInputContext(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetInputContext().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputContextMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInputContext() {
      return getInputContextMap();
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getInputContextMap() {
      return internalGetInputContext().getMap();
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getInputContextOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInputContext().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getInputContextOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInputContext().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearInputContext() {
      internalGetMutableInputContext().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */

    public Builder removeInputContext(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableInputContext().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableInputContext() {
      return internalGetMutableInputContext().getMutableMap();
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */
    public Builder putInputContext(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableInputContext().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * ctx 中的变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; input_context = 3;</code>
     */

    public Builder putAllInputContext(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableInputContext().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.kato.pro.risk.GrpcGroovyTestRequest)
  }

  // @@protoc_insertion_point(class_scope:com.kato.pro.risk.GrpcGroovyTestRequest)
  private static final com.kato.pro.risk.grpc.GrpcGroovyTestRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kato.pro.risk.grpc.GrpcGroovyTestRequest();
  }

  public static com.kato.pro.risk.grpc.GrpcGroovyTestRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcGroovyTestRequest>
      PARSER = new com.google.protobuf.AbstractParser<GrpcGroovyTestRequest>() {
    @java.lang.Override
    public GrpcGroovyTestRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcGroovyTestRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcGroovyTestRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcGroovyTestRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kato.pro.risk.grpc.GrpcGroovyTestRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

