// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk.proto

package com.kato.pro.risk.grpc;

public interface GrpcRiskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kato.pro.risk.GrpcRiskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * PASS/BLOCK/REVIEW
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * PASS/BLOCK/REVIEW
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * 0-100
   * </pre>
   *
   * <code>int32 score = 3;</code>
   * @return The score.
   */
  int getScore();

  /**
   * <code>repeated string reason_codes = 4;</code>
   * @return A list containing the reasonCodes.
   */
  java.util.List<java.lang.String>
      getReasonCodesList();
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @return The count of reasonCodes.
   */
  int getReasonCodesCount();
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @param index The index of the element to return.
   * @return The reasonCodes at the given index.
   */
  java.lang.String getReasonCodes(int index);
  /**
   * <code>repeated string reason_codes = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reasonCodes at the given index.
   */
  com.google.protobuf.ByteString
      getReasonCodesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */
  int getExtDataCount();
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */
  boolean containsExtData(
      java.lang.String key);
  /**
   * Use {@link #getExtDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtData();
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtDataMap();
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */

  java.lang.String getExtDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; ext_data = 5;</code>
   */

  java.lang.String getExtDataOrThrow(
      java.lang.String key);

  /**
   * <code>string message = 6;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 6;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
